### ISSUE TITLE
add san.aq

### ISSUE THREAD

**Issue by SZRabinowitz** [738/awesome-url-shortener#23]
Really simple, no signup needed, allows you to upload small files or paste a text

**Comment by iam-py-test** [comment]
GSB lookup page: https://transparencyreport.google.com/safe-browsing/search?url=san.aq

**Comment by biden2020prez** [comment]
I saw that too, But I have met the website owner before, and I really think
it's safe. Also the google page says it asks users for personal
information, but if you look at the site there is no such thing.

Lastly, upon my request, the owner just open sourced it,
github.com/neutronscott/sanaq.

**Comment by biden2020prez** [comment]
Okay, I looked on virustotal and indeed it has two flags. I think these are false positives, unless it's phishing in a way I don't know.

To be clear, I honestly don't care whether this site makes it on the list, and somehow I feel like the owner doesn't either. I only found the site because he posted a shortened link somewhere and I decided to visit san.aq. It doesn't even show in Google Searches. 


Now, it's my goto url shortener since it provides the shortest urls i've seen. Anyways, thanks for this repo and good luck. I am keeping this open in case the owner of this repo would like to add the url, but feel free to close it anytime.

**Comment by iam-py-test** [comment]
I guess maybe there was a malicious link which caused Google and other venders to start flagging it.

**Comment by neutronscott** [comment]
I'm sure there's junk on it. I really ought to expire links from anonymous folks. I never thought it would be found. :)

**Comment by biden2020prez** [comment]
> I'm sure there's junk on it. I really ought to expire links from anonymous folks. I never thought it would be found. :)

Never thought the site would be found or that the junk would be found?
